apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-pv
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-pv
      persistentVolumeClaim:
      claimName: test-pvc
