apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
spec:
  selector:
    app: myapp
    type: front-end
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80
