apiVersion: v1
kind: Pod
metadata:
  name: "simple-webapp-secret"
  labels:
    app: "simple-webapp-secret"
spec:
  containers:
    - name: simple-webapp-secret
      image: "sentinelfoxinc/sf-web-app-py:v1"
      envFrom:
        - secretRef:
            name: app-secret
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-secret-svc
spec:
  selector:
    app: simple-webapp-secret
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
