apiVersion: v1
kind: Pod
metadata:
  name: "simple-webapp-env"
  labels:
    app: "simple-webapp-env"
spec:
  containers:
    - name: simple-webapp-env
      image: "sentinelfoxinc/sf-web-app-py:v1"
      env:
        - name: APP_COLOR
          value: "blue"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-env-svc
spec:
  selector:
    app: simple-webapp-env
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
